# Generated by Django 3.1.7 on 2021-04-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210407_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pic',
            field=models.ImageField(default='white.png', upload_to='user_images', verbose_name='Добавить фото'),
        ),
    ]
