# Generated by Django 3.1.7 on 2021-04-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210407_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='pic',
        ),
    ]
